### ISSUE TITLE
Won't connect to wifi

### ISSUE THREAD

**Issue by duindain** [openipcamera/openipc-firmware#10]
Hi,
I've just flashed this to my camera and it is continuously flashing blue and orange which indicates no connection to wifi?

The camera was previously flashed with fang-hacks for several months with no issues, I reverted it back to stock firmware yesterday also with no issues connecting to wifi in both versions

I have configured my SSID and Wifi password as the only contents of the relevant files

My ssid contains an underscore if that could cause an issue but I changed it to not use it and it still couldn't connect

Is there a log thats readable? i see the binary log file on the sd card its around 1.2 mb but I cant read it
I can see the camera is taking video in the video folder on the sd card and pulling the sd card and reslotting it beeps as it should but no wifi

Also I tried the scanwifi script and it has a substitution error on line 24 on linux 

My ssid is 27 characters long, the password is 20 characters long using WPA 2

**Comment by duindain** [comment]
I followed this guide [](https://iotrant.com/2018/02/13/openipc-making-the-wyzecam-more-useful/) and managed to get the camera working

I had to use the barcode scanning method to get it onto wifi then check router for IP address

**Comment by waspinator** [comment]
can you explain what barcode scanning method you used?
