### ISSUE TITLE
Unable to flash Wyze V2

### ISSUE THREAD

**Issue by williamrussellajb** [openipcamera/openipc-firmware#106]
I have followed the install instructions. 

1. 512 MB SD Card
2. Copied everything from firmware_mod to the root directory
3. Updated the WIFI SSID and PW.
4. Inserted the SD Card
5. Held the settings button
6. Inserted the power
7. Continued holding for 3-10 seconds (tried various)

The girl always comes on "ready to connect" every 10 seconds. I cannot get it to boot into the teal color. 

Not sure what I am doing wrong.

**Comment by williamrussellajb** [comment]
Tried 4 different SD Cards. 

I ended up placing one inside an old android phone, let the android format it for me... and it worked.

FAT32 on Windows 10, and MAC didn't work for me.

**Comment by jeffvosburgh** [comment]
I know this is closed, but I'm having the same problem.  I did everything above plus tried formatting the SD card with the Wyze Cam v2 utilizing the stock firmware.   I've update 2 cameras in the last two days successfully with this same batch of SD cards with 0 issues.
