### ISSUE TITLE
openipcscan.sh: line 37: nmap: command not found

### ISSUE THREAD

**Issue by goldiiii** [openipcamera/openipc-firmware#21]
Hi guys.

On Windows, Mac and RaspberryPi Zero i get this error when running the openipcscanwin.sh and openipcscan.sh:

openipcscan.sh: line 37: nmap: command not found

Second question When do i have to insert the SD Card. Before step one?

**Comment by goldiiii** [comment]
sudo apt-get install nmap

solved it on the raspberry.

I still need to know when to insert the SD card into the camera

**Comment by openipcamera** [comment]
Please read the Wiki.
