### ISSUE TITLE
V2 arrived today

### ISSUE THREAD

**Issue by jbeck22** [openipcamera/openipc-firmware#23]
I received my V2 camera today.  I was able to get the sdcard flashed and I think it is loading to the camera, but I'm currently getting the 404 error when I go to /cgi-bin/status.cgi.  I tried removing and reinserting the card a few times. I get the "noise" but still get the 404 error afterwards. 

hello.cgi gives me:
snx_autorun.sh

bootstrap

System Volume Information

FIRMWARE_660R.bin

time_lapse

record

wlansetup.sh

log_A4DA222A2FAC_20180410113909_s.txt

Any ideas on what I can do to get this working?

#14

**Comment by bmac6996** [comment]
Just got mines too.

It has an orange light underneath.  But for me, it just says "waiting to connect" and nothing happens.  Doesn't look like it's joining anything.  Never turns solid. 

Can help troubleshoot if needed.

**Comment by maddios** [comment]
I don't think this project is compatible with the V2 yet, looks like the V2 flash process requires a "demo.bin" instead of a "FIRMWARE_660R.bin" file to be present

**Comment by mitchoklemen** [comment]
internal is probably more like Xiaomi Dafang, so...
https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks

**Comment by maddios** [comment]
really? which one? I tried one earlier today and had no luck at all

**Comment by REZ33W** [comment]
EliasKotlyar/Xiaomi-Dafang-Hacks.

**Comment by maddios** [comment]
Hm, I tried that one, how did you do it exactly? I basically popped it in and booted up while holding the button until blue light came on, then waited 5 minutes. 

then configured wpa supplicant as described, changing ssid and pw, but my light never went solid blue. just flashing.

**Comment by REZ33W** [comment]
Download CFW-Binary.
Format your microSD to FAT. NTFS, EXFAT etc. won't work.
Put it to microSD and rename it to "demo.bin". There should be no other files on the microSD! This is really important and it won't work if there are any other files on there.
Shutdown the camera, remove the power cable and plug the microSD
Hold the setup button on the camera
Plug in the USB power cable
Hold for about 10 secs
(edited from original)

**Comment by maddios** [comment]
Hm, that's basically what I did, maybe i screwed up the wpa_supplicant config, I do have a mesh, maybe it's confused by it? but the default wyze works fine.

**Comment by REZ33W** [comment]
I did not install new firmware just the bootloader. Still working on firmware install on V2.

**Comment by maddios** [comment]
Oh, I misread your original post, you haven't gotten it fully working, you just got the chinese prompt (flashed demo.bin). Oops.

Yeah I'm prob around the same point. I need to take mine apart and solder on the ftdi adapter so i can check what it's doing

**Comment by REZ33W** [comment]
Keep us updated. Thanks.

**Comment by openipcamera** [comment]
@REZ33W 
@maddios 

I am working on this as well. If anyone wants to join visit #openipc on freenode.
Thanks.

**Comment by openipcamera** [comment]
V2 alpha is available in releases

**Comment by MatthewNinety** [comment]
V2 alpha is working completely for me!

**Comment by derspion318** [comment]
Anyone else having an issue with the "Auto Night Mode"?
