### ISSUE TITLE
Support for Xiaofang 1s? 

### ISSUE THREAD

**Issue by newsera** [openipcamera/openipc-firmware#24]
https://en.xiaomitoday.it/xiaofang-1s-e-la-nuova-ip-camera-di-xiaomi.html

Does this hack script support the newer Xiaofang 1s?

**Comment by phineasthecat** [comment]
Looks like the XiaoFang 1s is basically the same hardware as the Wyzecam V2, so not yet. See this issue:
#23

**Comment by openipcamera** [comment]
Check v2 alpha
