### ISSUE TITLE
Trouble connecting to WiFi

### ISSUE THREAD

**Issue by waspinator** [openipcamera/openipc-firmware#26]
Thanks for working on making an open version of the firmware for this camera.

I think I followed the instructions correctly, but I can't connect to WiFi. This is what I did:

1. Flashed 0.2.4 using etcher
2. edited `.wifissid` and `.wifipasswd` with my SSID and wifi password
   - I'm not sure if I was supposed to keep the original "SSID" and "password" text in the file, but I just replaced them
3. Held down the "setup" button for 10 seconds (before connecting to power)
4. Still holding the "setup" button, connected to power
5. Let go of the button when the light blinks yellow-blue
6. Pressed the "setup" button again for a moment
7. Removed the SD card
8. Unplugged the USB cable
9. Plugged in the USB cable
10. Wait for status light to blink yellow-blue
11. Connect SD card
12. heard "click click"

At this point the status LED just blinks yellow-blue forever

I can connect to WiFi and get a solid blue led using the Mi Home app for Android. Then I can plug in the SD card and after hearing a "click click" I can accessss the `/cgi-bin/status` page, but after rebooting it looses connect and blinks yellow-blue again.

I tried going to `cgi-bin/network` and changing the Wireless mode from "cloud" to "Wireless Client", and selecting my WiFi SSID and entering the password. After clicking "connect" the light started blinking yellow-blue for a while and then blinking "blue". I could access `cgi-bin/status`, but after going back to `cgi-bin/network` the settings weren't updated. 

I can start "rescue telnetd" ~~but I don't know what the iSmartAlarm login name and password is~~. The username is "root" and the password is "ismart12"

I flashed 0.2.4, but the top of the page says "OpenIPC Version 0.2.2"

How do I set up the camera to connect to a wifi connection without using Mi Home? The changes I make in the `cgi-bin` pages don't seem to have any affect.

**Comment by openipcamera** [comment]
Make the changes in the .wifi config files.
Insert into camera until you hear click click
Reboot camera should be on network
