### ISSUE TITLE
Two features to make openIPC really stand out IR Heat Control & RTSP check service

### ISSUE THREAD

**Issue by zikzak82** [openipcamera/openipc-firmware#29]
Great work w/ this fork thus far. Enjoy seeing thorough notations, instructions, and roadmaps for future improvements. 

IR Heat Control, which fanghacks has some issue commentary, pulls, and a commit for
https://github.com/samtap/fang-hacks/issues/61
https://github.com/samtap/fang-hacks/pull/67
https://github.com/samtap/fang-hacks/pull/67/commits/01f302eca1bb71b2581d042c5f971f5a0c6dde5f

https://github.com/samtap/fang-hacks/commit/47e320c0fa775bf037a9f664ea008006da2db0e4aaaaaaa
https://github.com/samtap/fang-hacks/blob/0d2913f11b6bcf471f97e7bb29e6d4b5777c1dbf/usr/bin/fang-ir-control.sh

and this pull request for a watchdog script for the RTSP server to help restart the server automatically if it should ever shut down or for those with needing to restart the RTSP server every few days (could be heat, but that's def not always the case).

https://github.com/samtap/fang-hacks/pull/338

**Comment by openipcamera** [comment]
The rtsp watchdog is in v.0.2.4. V1 hardware will no longer be supported moving forward to v2 hardware.

Will look into rtsp heat

**Comment by zikzak82** [comment]
Thanks for the information...did I miss it documented in the readme/rls notes? If not, def add it as it's welcome feature that when manually adding to fanghacks-- broke stuff.

**Comment by claell** [comment]
@openipcamera I guess your plan on dropping support for V1 is no longer the case since the newest release supports both models again. So I think this should be reopened then if not already implemented.
