### ISSUE TITLE
Version 0.24 installed, buttons don't work

### ISSUE THREAD

**Issue by richardtheb** [openipcamera/openipc-firmware#32]
Hey, I installed 0.24 on one of my cameras, and got it running after some hassle. I now get the screen asking about Xiao Feng hacks and other options, but none of the buttons seem to do anything. Whatever option Is elect (including reset) comes back to the same status screen. The screen is updated, but there are no additional options, etc. 

Any ideas?

**Comment by openipcamera** [comment]
You need to click install hacks.

**Comment by richardtheb** [comment]
I did, and that made no difference. No change from that or any other button.

**Comment by richardtheb** [comment]
Ah, figured it out. I changed the name from iSmartAlarm to OpenIPC1, and hit set. I am wondering if having several cameras on the network (I have 3) was confusing it.
