### ISSUE TITLE
Date and time settings are wrong after restart, even with working ntp-server set

### ISSUE THREAD

**Issue by PH89** [openipcamera/openipc-firmware#45]
After setting a proper ntp-server in setting, the time gets update properly, however after a power re-cycle the time is not getting synced after the devices booted up.

**Comment by wayne47git** [comment]
Looking at the install, I'm not sure it can work:
```
[root@openipc:init.d]# find / -name ntpd -print
/usr/sbin/ntpd
[root@openipc:init.d]# /usr/sbin/ntpd
ntpd: applet not found
[root@openipc:init.d]# ls -l /usr/sbin/ntpd
lrwxrwxrwx    1 1000     1000            17 Mar 16 22:37 /usr/sbin/ntpd -> ../../bin/busybox
```

**Comment by PH89** [comment]
Since ntpd is laying on sdcard.
See my PR: https://github.com/openipcamera/openipc-firmware/pull/46
