### ISSUE TITLE
V2 cam, doesn't seem to work

### ISSUE THREAD

**Issue by ejo4041** [openipcamera/openipc-firmware#49]
I followed the instructions for V2: flashed the SD card, inserted, light was blue after power on while holding down button, released the button.  The camera rebooted and I heard the single click and the light is yellow now.  I've had the openipcscanwin.sh running waiting for it to come on, gave it more than an hour, still nothing, light is still yellow.

How would I go about debugging this?  I do believe the SSID and PW are correct, I disconnected my laptop and forgot it, used the same credentials I copied and pasted into the wpa file.  Any thoughts?

FW version is 4.9.1.42 on the camera and I have connected it through the Wyze Cam app when I got it.  It still works with the app if I pull out the sd card and reboot it.

**Comment by PH89** [comment]
For debugging: It would help if you can provide a boot log via the serial interface see:
https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/hacks/serial.md

If this is not possible try:
- using different sdcard.
- using different flashing method: https://etcher.io

**Comment by hofmand** [comment]
Is there a way to enable logging to the SD card? My symptoms match @ejo4041 's.

**Comment by PH89** [comment]
@hofmand Not as far as I know.

**Comment by mrpatg** [comment]
Try accessing the camera's IP via HTTP and see if you can reach it.

I had a similar issue where the light just never turned blue, but it was on and running.

**Comment by PH89** [comment]
After the cam is up and running the LED **should light yellow**. 
Keep in mind that the network ip range is statically set in the openipcscanwin.sh script. This means you may have to change the script in order to work properly for your network.

I guess your cam is working normally, but didn't found it.

May be you should try finding the cam in the DHCP leases list, that is normally within the web interface of your router.

**Comment by hofmand** [comment]
@PH89 The camera shows up in the DHCP leases list (maybe it's a stale entry) but I can't ping it or connect to it with http or ssh. There is no openipcscanwin.sh script on the SD image.

**Comment by PH89** [comment]
@hofmand openipcscanwin.sh is a script for finding the camera in local network and its not on the sdcard but in the repo.
If you found out the ip of the camera then you dont need to use it.

> maybe it's a stale entry
Maybe you can delete this entry to make sure you have the right IP. Does the mac address match with the mac address on the device sticker?

**Comment by hofmand** [comment]
Ok, I'm a doofus. I installed a wireless mesh router (Google Wifi) to improve the wireless coverage in my house. The mesh router is connected to the main router with ethernet, and the main router's wireless is turned off. The mesh router uses NAT, so my main computer which also connects to the main router couldn't talk to the camera. Anyway, it's working now, thanks! (BTW, Google Wifi doesn't let you delete DHCP entries so troubleshooting is difficult.)

**Comment by PH89** [comment]
@hofmand Interesting setup NAT between WiFi and Ethernet. Good that it is working now.

**Comment by svtcontour** [comment]
So if I have an ip range in the 192.168.0.1-254 I need to change this line of code in openipcscanwin.sh to refelct that?

Old code:
`#scan local network for rtsp cameras
	echo "Searching for OpenIP/Fanghacks cameras:"
	nmap -p80 **192.168.1.0/24** -oG - | awk '/open/ {print $2}' > ~/camlist.txt`

New code:
`#scan local network for rtsp cameras
	echo "Searching for OpenIP/Fanghacks cameras:"
	nmap -p80 **192.168.0.0/24** -oG - | awk '/open/ {print $2}' > ~/camlist.txt`

**Comment by PH89** [comment]
@svtcontour That’s correct.

**Comment by fellowgeek** [comment]
I cant find the openipcscanwin.sh script and I have the same problem, camera does not show up in network

**Comment by PH89** [comment]
> I cant find the openipcscanwin.sh script 

Its in the root directory of the repo. If you want to use it, make sure that the network address fits yours.
You can also try finding your camera in the web interface of your router or dhcp server. (Look for DHCP-Leases table)

> Camera does not show up in network

A few points to check:
- Please make sure that your PC and the camera are in the same network / subnet.
- Also make sure that your Wifi-Credentials are correct.
- Please keep also in mind that the cam only supports 2.4GHz Wifi not the 5GHz standard.

If nothing of this helps try:
- using different sdcard.
- using different flashing method: https://etcher.io

**Comment by fellowgeek** [comment]
thanks, got it working, the camera can only connect to 2.4 Ghz networks.

**Comment by PH89** [comment]
@ejo4041 Could you fix your problem also? If so, you may close this issue?

**Comment by ejo4041** [comment]
The openipcscanwin.sh never found anything.  I opened Zenmap and did a 
`nmap -sn 192.168.1.0/24`
Which showed me a MAC that looked similar to the C8:02:8F...
That was the correct ip and I can not get to the server.

The light is still yellow, but it seems like everything is working.

**Comment by PH89** [comment]
@ejo4041 Good that it is working now.
As I said the yellow light is normal here ( unlike the stock rom).
