### ISSUE TITLE
rtsp audio

### ISSUE THREAD

**Issue by cengelbracht** [openipcamera/openipc-firmware#5]
Was searching for anything related to audio under openipc to resolve my missing audio and saw your post: "Outside of a few minor modifications (wifi/remove rtsp audio)"

Can you clarify why rtsp audio was removed? I wanted to put a couple of these in bird houses and it would be nice to have the audio.

Thanks for your efforts and nice work! This setup method is significantly easier.

**Comment by lildevilx** [comment]
Agreed with the issue. Would love to have audio over rtsp working as well. 

Thanks for making flashing this hack much easier tho!
Keep up the great work.

**Comment by openipcamera** [comment]
Find /data/etc/scripts/20-rtsp-server Change

    snx_rtsp_server -W 1920 -H 1080 -Q 10 -b 4096 >$LOG 2>&1 &

to

    snx_rtsp_server -W 1920 -H 1080 -Q 10 -a -b 4096 >$LOG 2>&1 &

in our testing the audio option tends to make the rtsp unstable after a few days and may require a manual reset of the process in the web interface

I will make this feature on/off via web interface.

**Comment by lildevilx** [comment]
in the web interface under script, for the V1 there is an option to enable audio there

**Comment by mralexgray** [comment]
@lildevilx what about for v2?
