### ISSUE TITLE
Synology only 1-second recordings

### ISSUE THREAD

**Issue by hofmand** [openipcamera/openipc-firmware#53]
After successfully adding the camera (V2) to Synology Surveillance Station using the following values:
```
Port: 8554
Brand: [User Define]
Source path: /unicast
username: dafang
password: ismart12
```
Surveillance Station only records 1-second clips, and a lot of them.

If I try to change any settings under `IP Camera` &rarr; (camera) &rarr; `Edit`, I get the following error:
```
Failed to load camera capabilities values.
```
I wonder if the problem reading values is causing the 1-second clips.

**Comment by FuzzyMistborn** [comment]
Disable the audio

**Comment by hofmand** [comment]
@FuzzyMistborn Thanks, that worked! `IP Camera` &rarr; (camera) &rarr; `Edit` &rarr; `Device Settings` &rarr; `Video` &rarr; `Audio format: [Disable]`
