### ISSUE TITLE
Unable to flash Openipc FW (Fang-hacks works) 

### ISSUE THREAD

**Issue by theirishkiwi** [openipcamera/openipc-firmware#57]
**correction: I'm using Xiaomi-Dafang-Hacks, not Fang-hacks. 

Hi,

I've not been able to flash Openipc fw. I've been unable to get it to boot successfully. But I was able to get https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks to work. 

Could you show me the steps to patch the working fang-hacks build to openipc? I've tried combining the two, but no luck so far.

One thing I have noticed is run.sh references "/system/sdcard/config" , but I cannot find this directory.

cheers
Chris

**Comment by openipcamera** [comment]
You're trying to run the firmware for Wyze V2 on the V1 hardware. Please read the whole README.

**Comment by openipcamera** [comment]
Edit: run.sh only works on v2

**Comment by theirishkiwi** [comment]
Hi, 

As far as I understand, the cameras I have are v2 as they use audio prompts when setting camera up. I have also read all of the reade.

Regards
Chris

**Comment by openipcamera** [comment]
samtap only works on v1.

**Comment by theirishkiwi** [comment]
I'm using

**Comment by FuzzyMistborn** [comment]
OpenIPC is a fork of Dafang-Hacks.  There's no need to try to integrate the two.

**Comment by theirishkiwi** [comment]
Is there a way to patch a working Dafang-hacks build to Openipc? The openipc fork has quite a number of developments I'd like to use over Dafang-hacks.

Not sure why I can't get the openipc fork to work? Any help or guidance would be much appreciated.

**Comment by openipcamera** [comment]
There is no difference other than openipc works on Wyze

**Comment by openipcamera** [comment]
the kernel differs between dafang-hacks and openipc.
