### ISSUE TITLE
can't expand filesystem

### ISSUE THREAD

**Issue by mhertel** [openipcamera/openipc-firmware#60]
I noticed it wasnt using the full SD card capacity so I tried to expand it from the command line..
but i'm getting this:

/system/sdcard/bootstrap/resize2fs: line 1: syntax error: unexpected word (expecting ")")

I get the same error trying to run e2fsck as well.

Running a Wyzecam v2

**Comment by openipcamera** [comment]
Use the new method to create an sdcard.
