### ISSUE TITLE
Firmware Gone Missing

### ISSUE THREAD

**Issue by johnnyq** [openipcamera/openipc-firmware#63]
Hello it looks like openipc_v2-0.2.5.img is missing and there doesnt appear to be one for 0.2.6 img
Did a google search, pulled up cached entry and saw that file was last seen on May 20
https://github.com/openipcamera/openipc-firmware/releases/download/0.2.5/openipc_v2-0.2.5.img
I really want to try this please restore the file. Thanks

**Comment by astronaut701** [comment]
Same here, I would to see it be uploaded or know how to build the img file for 0.2.5 and 0.2.6.

**Comment by chrisb22** [comment]
Please someone share the 0.2.5 and 0.2.6 img files again. Thanks!

**Comment by phantomdarkness** [comment]
You can install the firmware from https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks

**Comment by hofmand** [comment]
https://github.com/openipcamera/openipc-firmware/archive/0.2.5.zip

**Comment by astronaut701** [comment]
Thanks hofmand for finding the 0.2.5 files! But the 0.2.6 firmware (img file) for some reason isn't out which contains fixes for IR (AKA Night Vision for the camera). (Through automatic switching for IR isn't available yet, you have to manually turn it on and off.)

**Comment by openipcamera** [comment]
Check the new README on how to create an sdcard from the repo.

Installation Instructions Wyze V2:

This process only works for Wyze V2. There are no flashing LED or sound effects from V1.

    Download this git repository.

    Copy the contents of firmware_mod/v2/ to the root of your sdcard.

    Set up Wifi in the SD card config folder wpa_supplicant.conf

    Power off your camera, insert the SD card
