### ISSUE TITLE
snx_rtsp_server stops running

### ISSUE THREAD

**Issue by brmo** [openipcamera/openipc-firmware#8]
I check my NVR at random times and see the video is not streaming. Check the cam and the snx_rtsp_server is not running. Any reason why this could be?  I was going to run a cronjob to check every minute if the process is running, but it seems I cannot do that either.

**Comment by openipcamera** [comment]
a cronjob should solve this

**Comment by brmo** [comment]
Seems there is no cron support built in. So as I stated, that wouldn't work.  However I believe I figured it out, I use motioneye for my NVR, and it seems the capture was doing so at 5 FPS, when i flipped it to record at 10 FPS, it hasn't crashed in over 24 hours.
