### ISSUE TITLE
I cannot seem to get the a rtsp://[discoveredipaddress]/unicast

### ISSUE THREAD

**Issue by sreed77** [openipcamera/openipc-firmware#9]
first off let me say thanks for doing this work to make our camera more than they are. I'm having a problem where I cannot access the camera by rtsp. I'm able to access the camera webpage and have it set using the default setting is there something that I missed?

**Comment by dasmoover** [comment]
try version 0.2.2 see if it works

**Comment by openipcamera** [comment]
try version 0.2.2

**Comment by sreed77** [comment]
ok I fix  my problem this is the steps I followed after the Chinese message Eject the card. remove usb cable. Plug power back in. The blue/yellow light will blink, wait 20 more seconds - put sd card than click apply fang hacks
